<?php

namespace JT\MenuComposerBundle\Repository;

/**
 * CprMenuItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CprMenuItemRepository extends \Doctrine\ORM\EntityRepository
{
}
