<?php

namespace JT\MenuComposerBundle\Repository;

/**
 * CprMenuDropdownRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CprMenuDropdownRepository extends \Doctrine\ORM\EntityRepository
{
}
