<?php

namespace JT\MenuComposerBundle\Repository;

/**
 * CprMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CprMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
