<?php

namespace JT\MenuComposerBundle\Repository;

/**
 * CprMenuSubDropdownRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CprMenuSubDropdownRepository extends \Doctrine\ORM\EntityRepository
{
}
