<?php

namespace JT\PageComposerBundle\Repository;

/**
 * CprBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CprBlockRepository extends \Doctrine\ORM\EntityRepository
{
}
