<?php

namespace JT\PageComposerBundle\Repository;

/**
 * CprColumnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CprColumnRepository extends \Doctrine\ORM\EntityRepository
{
}
