<?php

namespace JT\PageComposerBundle\Repository;

/**
 * CprColumnBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CprColumnBlockRepository extends \Doctrine\ORM\EntityRepository
{
}
