<?php

namespace JT\PageComposerBundle\Repository;

/**
 * CprPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CprPageRepository extends \Doctrine\ORM\EntityRepository
{
}
