<?php

namespace JT\PageComposerBundle\Repository;

/**
 * CprRowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CprRowRepository extends \Doctrine\ORM\EntityRepository
{
}
