<?php

namespace JT\GaleryBundle\Repository;

/**
 * CprGaleryBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CprGaleryBlockRepository extends \Doctrine\ORM\EntityRepository
{
}
