<?php

namespace JT\GaleryBundle\Repository;

/**
 * CprGaleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CprGaleryRepository extends \Doctrine\ORM\EntityRepository
{
}
