<?php

namespace JT\FormComposerBundle\Repository;

/**
 * CprFormFieldListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CprFormFieldListRepository extends \Doctrine\ORM\EntityRepository
{
}
