<?php

namespace JT\FormComposerBundle\Repository;

/**
 * CprFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CprFormRepository extends \Doctrine\ORM\EntityRepository
{
}
