<?php

namespace JT\FormComposerBundle\Repository;

/**
 * CprFieldOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CprFormFieldOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
