<?php

namespace JT\FormComposerBundle\Repository;

/**
 * CprFormConditionGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CprFormConditionGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
