<?php

namespace JT\FormComposerBundle\Repository;

/**
 * FormResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CprFormResponseRepository extends \Doctrine\ORM\EntityRepository
{
}
