<?php

namespace JT\FormComposerBundle\Repository;

/**
 * CprFormConditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CprFormConditionRepository extends \Doctrine\ORM\EntityRepository
{
}
