<?php

namespace JT\FormComposerBundle\Repository;

/**
 * CprFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CprFormFieldRepository extends \Doctrine\ORM\EntityRepository
{
}
